// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_XtVX
NumericVector cpp_XtVX(List Qlist, List Alist, IntegerVector ind1, IntegerVector ind2);
RcppExport SEXP _MetaHD_cpp_XtVX(SEXP QlistSEXP, SEXP AlistSEXP, SEXP ind1SEXP, SEXP ind2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Qlist(QlistSEXP);
    Rcpp::traits::input_parameter< List >::type Alist(AlistSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ind1(ind1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ind2(ind2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_XtVX(Qlist, Alist, ind1, ind2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MetaHD_cpp_XtVX", (DL_FUNC) &_MetaHD_cpp_XtVX, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_MetaHD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
